优化README文案和格式
WeBankFinTech/WeTrident pull request #9
Opened 2019-12-17 12:36 UTC by lhtin

2019-12-18 03:18 UTC, erichua23 requested changes

2019-12-18 03:18 UTC, erichua23 commented on README.md
> +WeTrident目前仅支持macOS操作系统。通过使用cli初始化项目，如果有任何相关问题，WeTrident会提示出来以便协助你解决。开发前需要先配置Android和iOS开发环境，具体配置方法可以参考Android和iOS官方文档。
通过使用 @webank/trident-cli 初始化项目

2019-12-18 03:18 UTC, erichua23 commented on package.json
> +  "description": "可快速开发、支持商业运营的App框架。",
一站式金融App开发套件。

2019-12-18 03:18 UTC, erichua23 commented on README.md
> +3. **提供丰富完整的调试信息**：统一将请求、修改状态等操作的日志统一输出，提到调试效率。
这里跟前后统一一下用一套？

2019-12-18 03:18 UTC, erichua23 commented on README.md
> +可快速开发、支持商业运营的App框架。
一站式金融App开发套件。

2019-12-19 08:17 UTC, lhtin commented on README.md
> +3. **提供丰富完整的调试信息**：统一将请求、修改状态等操作的日志统一输出，提到调试效率。
是指跟哪里统一？

2019-12-24 07:12 UTC, erichua23 approved these changes

2019-12-24 07:12 UTC, merged